"""Stage 5: Collect external data sources (real-world, LLM, GPTZero, journal).

Each sub-stage loads or generates entries from a specific external source.
All return lists of BenchmarkEntry ready for integration.
"""

from __future__ import annotations

import logging
from pathlib import Path

from hallmark.dataset.schema import BenchmarkEntry, load_entries

logger = logging.getLogger(__name__)


def stage_collect_real_world(build_date: str) -> list[BenchmarkEntry]:
    """Collect real-world hallucination entries from documented incidents.

    Deterministic: hardcoded entries from GPTZero, HalluCitation, GhostCite studies.
    Imports functions from collect_real_world_citations.py.
    """
    try:
        from scripts.collect_real_world_citations import (
            create_ghostcite_entries,
            create_hallucitation_acl_entries,
            create_neurips_2025_entries,
        )
    except ImportError:
        # Fallback: try importing with path manipulation
        import importlib.util
        import sys

        script_path = Path(__file__).parent.parent / "collect_real_world_citations.py"
        if not script_path.exists():
            logger.error("Cannot find collect_real_world_citations.py at %s", script_path)
            return []

        spec = importlib.util.spec_from_file_location("collect_rw", script_path)
        if spec is None or spec.loader is None:
            logger.error("Cannot load collect_real_world_citations.py")
            return []
        mod = importlib.util.module_from_spec(spec)
        sys.modules["collect_rw"] = mod
        spec.loader.exec_module(mod)

        create_neurips_2025_entries = mod.create_neurips_2025_entries
        create_hallucitation_acl_entries = mod.create_hallucitation_acl_entries
        create_ghostcite_entries = mod.create_ghostcite_entries

    entries: list[BenchmarkEntry] = []
    entries.extend(create_neurips_2025_entries())
    entries.extend(create_hallucitation_acl_entries())
    entries.extend(create_ghostcite_entries())

    # Set build date on all entries
    for e in entries:
        e.added_to_benchmark = build_date

    logger.info("Collected %d real-world entries from 3 studies", len(entries))
    return entries


def stage_load_cached_llm(path: Path) -> list[BenchmarkEntry]:
    """Load pre-generated LLM hallucination entries from a JSONL file.

    These entries were generated by generate_llm_hallucinations.py using
    various LLM backends (GPT-4o, Claude, local models).
    """
    if not path.exists():
        logger.warning("LLM hallucinations file not found: %s", path)
        return []

    entries = load_entries(path)
    logger.info("Loaded %d LLM-generated entries from %s", len(entries), path)
    return entries


def stage_load_gptzero_seed(path: Path) -> list[BenchmarkEntry]:
    """Load hand-curated GPTZero seed entries from a JSONL file.

    These are specific examples from the GPTZero NeurIPS analysis,
    manually curated for quality.
    """
    if not path.exists():
        logger.warning("GPTZero seed file not found: %s", path)
        return []

    entries = load_entries(path)
    logger.info("Loaded %d GPTZero seed entries from %s", len(entries), path)
    return entries
