#!/usr/bin/env python3
"""Generate the filled-in LaTeX block for the cutoff-aware appendix table.

Reads default post-cutoff metrics (precomputed on the 2024-2025 supplement),
cutoff-aware post-cutoff metrics (from the ablation), the cutoff-aware pre-
cutoff metrics (from the 150-entry dev_public sample), and the pre-cutoff
default UNCERTAIN rates straight from the existing ``results/llm_*_dev_public.json``
eval files.

Emits ``paper/figures/cutoff_aware_results.tex`` — a single \\input-able
LaTeX block containing the post-cutoff comparison table, the pre-cutoff
UNCERTAIN rate table, and a short outcome-classification paragraph.
Intended to replace the ``\\todo{}`` placeholder in
``paper/appendix.tex`` (line ~759).

Usage::

    python scripts/emit_cutoff_aware_appendix.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from hallmark.dataset.schema import load_entries, load_predictions
from hallmark.evaluation.metrics import evaluate

# model_key -> (display, default post-cutoff eval json, cutoff-aware post eval,
#               cutoff-aware pre pred jsonl, default pre-cutoff dev_public eval)
MODELS: dict[str, dict[str, str]] = {
    "llm_openai": {
        "display": "GPT-5.1",
        "post_default": "results/temporal_supplement/llm_openai_temporal.json",
        "post_ca": "results/temporal_supplement/llm_openai_cutoff_aware_temporal.json",
        "pre_ca_preds": "results/precutoff_ablation/llm_openai_cutoff_aware_temporal_predictions.jsonl",
        "pre_default_eval": "results/llm_openai_dev_public.json",
    },
    "llm_openrouter_gemini_flash": {
        "display": "Gemini 2.5 Flash",
        "post_default": ("results/temporal_supplement/llm_openrouter_gemini_flash_temporal.json"),
        "post_ca": (
            "results/temporal_supplement/llm_openrouter_gemini_flash_cutoff_aware_temporal.json"
        ),
        "pre_ca_preds": (
            "results/precutoff_ablation/"
            "llm_openrouter_gemini_flash_cutoff_aware_temporal_predictions.jsonl"
        ),
        "pre_default_eval": "results/llm_openrouter_gemini_flash_dev_public.json",
    },
    "llm_openrouter_qwen": {
        "display": "Qwen3-235B",
        "post_default": "results/temporal_supplement/llm_openrouter_qwen_temporal.json",
        "post_ca": "results/temporal_supplement/llm_openrouter_qwen_cutoff_aware_temporal.json",
        "pre_ca_preds": "results/precutoff_ablation/llm_openrouter_qwen_cutoff_aware_temporal_predictions.jsonl",
        "pre_default_eval": "results/llm_openrouter_qwen_dev_public.json",
    },
}

PRECUTOFF_SAMPLE = Path("results/temporal_supplement/precutoff_sample.jsonl")
SUPPLEMENT = Path("results/temporal_supplement/temporal_supplement_2024_2025.jsonl")


def _pre_ca_eval(pred_path: Path, sample_path: Path) -> dict[str, Any]:
    preds = load_predictions(pred_path)
    entries = load_entries(sample_path)
    pred_keys = {p.bibtex_key for p in preds}
    entries = [e for e in entries if e.bibtex_key in pred_keys]
    res = evaluate(entries, preds, tool_name="pre_ca", split_name="precutoff_sample")
    d = res.to_dict() if hasattr(res, "to_dict") else res.__dict__
    # Uncertain rate from predictions directly.
    n_unc = sum(1 for p in preds if p.label == "UNCERTAIN")
    d["uncertain_rate"] = n_unc / len(preds) if preds else 0.0
    d["n_preds"] = len(preds)
    return d


def _pct(x: float | None) -> str:
    if x is None:
        return "--"
    return f"{x * 100:.1f}"


def main() -> None:
    out = Path("paper/figures/cutoff_aware_results.tex")
    rows: list[dict[str, Any]] = []
    for _mk, info in MODELS.items():
        post_d = json.loads(Path(info["post_default"]).read_text())
        post_ca_path = Path(info["post_ca"])
        pre_default_eval = json.loads(Path(info["pre_default_eval"]).read_text())
        pre_ca_path = Path(info["pre_ca_preds"])

        if not post_ca_path.exists():
            print(f"MISSING: {post_ca_path}", file=sys.stderr)
            continue
        if not pre_ca_path.exists():
            print(f"MISSING: {pre_ca_path}", file=sys.stderr)
            continue

        post_ca = json.loads(post_ca_path.read_text())
        pre_ca_metrics = _pre_ca_eval(pre_ca_path, PRECUTOFF_SAMPLE)

        row = {
            "model": info["display"],
            "post_default": post_d,
            "post_ca": post_ca,
            "pre_default_eval": pre_default_eval,
            "pre_ca": pre_ca_metrics,
            "pre_default_unc_rate": (pre_default_eval.get("num_uncertain", 0))
            / (pre_default_eval.get("num_entries", 1) or 1),
        }
        rows.append(row)

    # Build LaTeX
    lines: list[str] = []
    lines.append("% Auto-generated by scripts/emit_cutoff_aware_appendix.py")
    lines.append("% Replaces the \\todo{} placeholder in the cutoff-aware appendix.")
    lines.append("")
    lines.append("\\begin{table}[h]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append(
        "\\caption{Cutoff-aware ablation results. "
        "\\emph{Post-cutoff}: 2024--2025 temporal supplement ($N{=}448$ unique "
        "entries, all post-cutoff for the three tested models). "
        "\\emph{Pre-cutoff}: 150-entry stratified sample of "
        "\\textsc{dev\\_public} (2021--2023, pre-cutoff for all three models; "
        "75 \\textsc{valid}/75 \\textsc{hallucinated}). "
        "Default pre-cutoff \\texttt{UNCERTAIN} rates are taken from the full "
        "\\textsc{dev\\_public} evaluation. "
        "$\\Delta$ columns report cutoff-aware minus default.}"
    )
    lines.append("\\label{tab:cutoff-aware-results}")
    lines.append("\\resizebox{\\columnwidth}{!}{%")
    lines.append("\\begin{tabular}{lrrrrrr}")
    lines.append("\\toprule")
    lines.append(
        "& \\multicolumn{4}{c}{\\textbf{Post-cutoff} ($N{=}448$)}"
        " & \\multicolumn{2}{c}{\\textbf{Pre-cutoff} ($N{=}150$)} \\\\"
    )
    lines.append("\\cmidrule(lr){2-5}\\cmidrule(lr){6-7}")
    lines.append(
        "Model & FPR$_{\\text{def}}$ & FPR$_{\\text{CA}}$ & $\\Delta$FPR"
        " & UNC$_{\\text{CA}}$ & UNC$_{\\text{def}}$ & UNC$_{\\text{CA}}$ \\\\"
    )
    lines.append("\\midrule")

    for r in rows:
        pd = r["post_default"]
        pc = r["post_ca"]
        pre_ca = r["pre_ca"]
        pre_def_unc = r["pre_default_unc_rate"]
        # Post-cutoff cutoff-aware UNCERTAIN rate derived from predictions
        mk_for_row = next(k for k, v in MODELS.items() if v["display"] == r["model"])
        post_ca_pred_path = (
            Path("results/temporal_supplement")
            / f"{mk_for_row}_cutoff_aware_temporal_predictions.jsonl"
        )
        try:
            ca_preds = load_predictions(post_ca_pred_path)
            post_ca_unc_rate = sum(1 for p in ca_preds if p.label == "UNCERTAIN") / max(
                len(ca_preds), 1
            )
        except Exception:
            post_ca_unc_rate = pc.get("num_uncertain", 0) / max(pc.get("num_entries", 1), 1)

        d_fpr = pd["false_positive_rate"]
        c_fpr = pc["false_positive_rate"]
        delta_fpr = (c_fpr - d_fpr) * 100
        lines.append(
            f"{r['model']} & "
            f"{_pct(d_fpr)} & {_pct(c_fpr)} & {delta_fpr:+.1f} "
            f"& {_pct(post_ca_unc_rate)} "
            f"& {_pct(pre_def_unc)} & {_pct(pre_ca.get('uncertain_rate', 0.0))} \\\\"
        )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append("\\end{table}")
    lines.append("")
    # Outcome classification
    lines.append("\\paragraph{Outcome classification.}")
    if rows:
        # Use the most-tested signal: max FPR drop vs pre-cutoff UNCERTAIN inflation.
        max_fpr_drop = max(
            (r["post_default"]["false_positive_rate"] - r["post_ca"]["false_positive_rate"]) * 100
            for r in rows
        )
        max_pre_unc = max(r["pre_ca"].get("uncertain_rate", 0.0) for r in rows) * 100
        lines.append(
            f"Across the three tested models, the maximum post-cutoff FPR drop is "
            f"{max_fpr_drop:.1f}\\,pp and the maximum pre-cutoff \\texttt{{UNCERTAIN}} "
            f"rate under the cutoff-aware prompt is {max_pre_unc:.1f}\\%. "
        )
        if max_fpr_drop < 15 and max_pre_unc < 40:
            lines.append(
                "This triggers the first row of \\cref{tab:cutoff-aware-preregistration}: "
                "\\emph{strong H1 confirmation} -- the failure is epistemic, and prompting "
                "does not patch it."
            )
        elif max_pre_unc >= 40:
            lines.append(
                "This triggers the second row of \\cref{tab:cutoff-aware-preregistration}: "
                "\\emph{partial metacognition} -- the reminder reduces confident over-flagging "
                "but simultaneously inflates pre-cutoff abstention, consistent with loss of "
                "discrimination rather than a genuine temporal-awareness gain."
            )
        else:
            lines.append(
                "This triggers the third row of \\cref{tab:cutoff-aware-preregistration}: "
                "\\emph{H2 holds} -- the FPR drop is localised to post-cutoff entries "
                "while pre-cutoff \\texttt{UNCERTAIN} remains low, which reframes LLM-based "
                "verifiers as ``unreliable by default, mitigatable with explicit cutoff-aware "
                "prompting.''"
            )
    lines.append("")
    lines.append(
        "\\noindent Claude Sonnet~4.5 is omitted from the table because no Anthropic API key "
        "was available during this ablation run; we flag this as a coverage limitation."
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out}")

    # Also dump the raw numbers for logging / re-use.
    summary = {
        "rows": [
            {
                "model": r["model"],
                "post_default_fpr": r["post_default"]["false_positive_rate"],
                "post_ca_fpr": r["post_ca"]["false_positive_rate"],
                "post_default_dr": r["post_default"]["detection_rate"],
                "post_ca_dr": r["post_ca"]["detection_rate"],
                "post_default_unc_count": r["post_default"].get("num_uncertain"),
                "post_ca_unc_count": r["post_ca"].get("num_uncertain"),
                "pre_default_unc_rate": r["pre_default_unc_rate"],
                "pre_ca_unc_rate": r["pre_ca"].get("uncertain_rate"),
                "pre_ca_dr": r["pre_ca"].get("detection_rate"),
                "pre_ca_fpr": r["pre_ca"].get("false_positive_rate"),
                "pre_ca_n": r["pre_ca"].get("n_preds"),
            }
            for r in rows
        ]
    }
    summary_path = out.with_suffix(".json")
    summary_path.write_text(json.dumps(summary, indent=2))
    print(f"Wrote {summary_path}")

    # Console
    print("\n=== SUMMARY ===")
    for r in summary["rows"]:
        print(
            f"  {r['model']:18s}  "
            f"post FPR {r['post_default_fpr'] * 100:5.1f} -> {r['post_ca_fpr'] * 100:5.1f}  "
            f"pre UNC {r['pre_default_unc_rate'] * 100:5.1f} -> {r['pre_ca_unc_rate'] * 100:5.1f}"
        )


if __name__ == "__main__":
    main()
