"""Ingest the Walters & Wilder (2023) ChatGPT-citation dataset as a HALLMARK eval-only supplement.

Source
------
William H. Walters & Esther Isabelle Wilder, "Fabrication and errors in the
bibliographic citations generated by ChatGPT", Scientific Reports 13:14045 (2023).
https://doi.org/10.1038/s41598-023-41032-5  (CC BY 4.0)

The coded ground truth lives in Supplementary Appendix 3 (an .xlsx with two
sheets; we use "Works cited in those papers", 636 rows).  Each row is a single
bibliographic citation emitted by ChatGPT-3.5 or GPT-4, hand-coded by the authors
for fabrication and for substantive metadata errors.

Scope: supported types only
---------------------------
This supplement keeps only journal-article citations (the publication type that
academic citation verifiers actually resolve; books/chapters/websites are skipped
by DOI/CrossRef/DBLP/OpenAlex-based tools and are out of scope here).

Label mapping (faithful to the HALLMARK taxonomy)
-------------------------------------------------
A field mismatch on a real work is still a hallucination, so it is mapped to the
matching HALLMARK type rather than left VALID:

  * work itself fabricated            -> plausible_fabrication  (Tier 3)
  * real work, incorrect title        -> near_miss_title        (Tier 3)
  * real work, incorrect authorship   -> author_mismatch        (Tier 2)
  * real work, fabricated journal     -> nonexistent_venue      (Tier 1)
  * real work, incorrect (real) journal -> wrong_venue          (Tier 2)
  * real work, no substantive error   -> VALID

When several substantive fields are wrong, the most identity-defining field wins,
in the order title > author > fabricated-venue > wrong-venue; every wrong field is
still listed in the explanation.

Deliberately excluded
---------------------
Real articles whose ONLY substantive error is a wrong (non-future) year and/or a
wrong volume/issue/page are excluded: the work is real and unambiguously findable,
and the HALLMARK taxonomy has no type for a bare year/volume/page slip (future_date
requires a future year; none of these are future).  Formatting-only issues
(capitalization, quotes, first-name-vs-initials, missing page numbers) are NOT
treated as hallucinations.

Usage
-----
    python scripts/ingest_walters_wilder.py \
        --xlsx /path/to/41598_2023_41032_MOESM3_ESM.xlsx \
        --out data/v1.0/supplement_chatgpt_citations.jsonl

If --xlsx is omitted the appendix is downloaded from Springer.
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.request
from dataclasses import asdict
from pathlib import Path
from typing import Any

from hallmark.dataset.schema import (
    EXPECTED_SUBTESTS,
    VALID_SUBTESTS,
    BenchmarkEntry,
    HallucinationType,
)

APPENDIX3_URL = (
    "https://static-content.springer.com/esm/"
    "art%3A10.1038%2Fs41598-023-41032-5/MediaObjects/"
    "41598_2023_41032_MOESM3_ESM.xlsx"
)
SHEET = "Works cited in those papers"

# Column indices in the "Works cited" sheet (0-based).
C_GPT, C_FIELD, C_TOPIC, C_CNUM, C_CITE = 0, 1, 2, 3, 4
C_PUBTYPE = 8
C_VENUE_FAB = 12
C_WORK_FAB = 13
C_ERR_AUTHOR, C_ERR_TITLE, C_ERR_DATE = 15, 16, 17
C_ERR_JOURNAL, C_ERR_VOLPAGE = 18, 19

TIER = {
    HallucinationType.PLAUSIBLE_FABRICATION: 3,
    HallucinationType.NEAR_MISS_TITLE: 3,
    HallucinationType.AUTHOR_MISMATCH: 2,
    HallucinationType.WRONG_VENUE: 2,
    HallucinationType.NONEXISTENT_VENUE: 1,
}


def _is_one(v: Any) -> bool:
    return v == 1 or v == "1"


# --------------------------------------------------------------------------- #
# APA reference-string parsing
# --------------------------------------------------------------------------- #
def parse_apa_article(cite: str) -> dict[str, str]:
    """Best-effort parse of an APA journal-article reference into BibTeX fields."""
    cite = " ".join(str(cite).split())
    fields: dict[str, str] = {}

    # Year: APA "(YYYY)" first, then a Chicago-style bare " YYYY." fallback.
    m = re.search(r"\((\d{4}[a-z]?|n\.d\.)\)\.?", cite)
    if m:
        year = m.group(1)[:4]
        authors = cite[: m.start()].strip().rstrip(".,")
        rest = cite[m.end() :].strip()
    else:
        m2 = re.search(r"[.,]\s+((?:18|19|20)\d{2})\.\s", cite)
        if m2:
            year = m2.group(1)
            authors = cite[: m2.start()].strip().rstrip(".,")
            rest = cite[m2.end() :].strip()
        else:
            year, authors, rest = "", "", cite
    if year.isdigit():
        fields["year"] = year

    if authors:
        parsed = _clean_authors(authors)
        if parsed:
            fields["author"] = parsed

    title, journal = _title_and_journal(rest)
    if title:
        fields["title"] = title
    if journal:
        fields["journal"] = journal
    return fields


def _clean_authors(a: str) -> str:
    # An APA ellipsis / "et al." means the author list is intentionally
    # abbreviated; record that so it can be re-expressed as BibTeX "and others"
    # (i.e. et al.) rather than dropped, which would make a legitimately long
    # author list look silently truncated to a verifier.
    truncated = bool(re.search(r"…|\.\.\.|\bet\s+al\.?", a, flags=re.I))
    a = a.replace("…", " ").replace("...", " ")
    a = re.sub(r"\bet\s+al\.?", " ", a, flags=re.I)
    a = re.sub(r"\s{2,}", " ", a).strip().strip(",").strip().rstrip(".")
    # Standard APA: repeated "Lastname, I. I." units separated by commas/&.
    # The final initial may have lost its trailing period to the year-split, so
    # allow the last initial to be period-less (otherwise the final author of an
    # "A, B, & C" citation is dropped, faking an author-truncation).
    units = re.findall(
        r"([A-Z\u00c0-\u00dd][A-Za-z\u00c0-\u00ff'\u2019\-]+(?:\s+[A-Za-z\u00c0-\u00ff'\u2019\-]+)?),"
        r"\s*((?:[A-Z]\.\s*){0,3}[A-Z]\.?)",
        a,
    )
    if units:
        parts = []
        for last, inits in units:
            inits = re.sub(r"([A-Z])(?![.\w])", r"\1.", inits.strip())  # restore lost periods
            parts.append(f"{inits} {last.strip()}".strip())
        names = " and ".join(parts)
        if truncated:
            names += " and others"
        return names
    return a


def _title_and_journal(rest: str) -> tuple[str, str]:
    """Split "Title. Journal, vol(issue), pages." into (title, journal).

    The journal is anchored by the trailing "<Journal>, <volume>[(issue)], <pages>"
    locator, so titles that themselves contain periods, colons, quotes or a
    terminal "?" (common in humanities/social-science titles) are kept intact.
    """
    rest = rest.strip()
    if not rest:
        return "", ""
    # Journal starts after the last sentence-ender (optionally followed by a
    # closing quote) that precedes a "<Capitalised Journal Name>, <digits>"
    # locator.
    sep = r"[.?!][\u201d\"\u2019]?\s+"
    for m in reversed(list(re.finditer(sep, rest))):
        tail = rest[m.end() :]
        j = re.match(r"([A-Z][^.]*?),\s*\d", tail)
        if j:
            title = rest[: m.start() + 1].rstrip()  # keep terminal ? or !, drop bare .
            if title.endswith("."):
                title = title[:-1]
            return _clean_title(title), j.group(1).strip()
    # No locator: split at the first sentence break; everything after is venue.
    m = re.search(sep, rest)
    if m:
        journal = re.split(r",\s*\d", rest[m.end() :])[0].strip(" .,")
        return _clean_title(rest[: m.start() + 1]), journal
    return _clean_title(rest), ""


def _clean_title(t: str) -> str:
    return t.strip().strip(".").strip().strip('"').strip("\u201c\u201d").strip()


def _parse_ok(fields: dict[str, str]) -> bool:
    """Reject parses that are obviously broken (non-APA input the parser mangled)."""
    title = fields.get("title", "")
    year = fields.get("year", "")
    if not title or not year.isdigit() or not (1900 <= int(year) <= 2025):
        return False
    if len(title) < 15 or re.match(r"^[:;,.\d]", title):
        return False
    # A page-range tail in the title means title/journal never separated.
    return re.search(r",\s*\d+[-\u2013]\d+\s*$", title) is None


# --------------------------------------------------------------------------- #
# Label mapping
# --------------------------------------------------------------------------- #
def classify(row: tuple[Any, ...]) -> tuple[str, HallucinationType | None, str | None]:
    """Return (label, hallucination_type, decision) for one article row.

    decision is a short provenance tag; hallucination_type is None for VALID and
    the string "EXCLUDE" decision means the row is dropped from the supplement.
    """
    if _is_one(row[C_WORK_FAB]):
        return "HALLUCINATED", HallucinationType.PLAUSIBLE_FABRICATION, "fabricated"

    wrong_title = _is_one(row[C_ERR_TITLE])
    wrong_author = _is_one(row[C_ERR_AUTHOR])
    venue_fab = _is_one(row[C_VENUE_FAB])
    wrong_journal = _is_one(row[C_ERR_JOURNAL])
    wrong_date = _is_one(row[C_ERR_DATE])
    wrong_volpage = _is_one(row[C_ERR_VOLPAGE])

    if wrong_title:
        return "HALLUCINATED", HallucinationType.NEAR_MISS_TITLE, "title"
    if wrong_author:
        return "HALLUCINATED", HallucinationType.AUTHOR_MISMATCH, "author"
    if venue_fab:
        return "HALLUCINATED", HallucinationType.NONEXISTENT_VENUE, "venue_fab"
    if wrong_journal:
        return "HALLUCINATED", HallucinationType.WRONG_VENUE, "journal"

    if wrong_date or wrong_volpage:
        # Real, findable work with only a year/volume/page slip: no HALLMARK type.
        return "EXCLUDE", None, "date_or_volpage_only"
    return "VALID", None, "clean"


def _explanation(row: tuple[Any, ...], htype: HallucinationType | None) -> str:
    if htype == HallucinationType.PLAUSIBLE_FABRICATION:
        return "ChatGPT-fabricated citation: no such work exists (human-coded)."
    errs = []
    if _is_one(row[C_ERR_TITLE]):
        errs.append("incorrect title")
    if _is_one(row[C_ERR_AUTHOR]):
        errs.append("incorrect authorship")
    if _is_one(row[C_VENUE_FAB]):
        errs.append("fabricated journal name")
    if _is_one(row[C_ERR_JOURNAL]):
        errs.append("incorrect journal")
    if _is_one(row[C_ERR_DATE]):
        errs.append("incorrect year")
    if _is_one(row[C_ERR_VOLPAGE]):
        errs.append("incorrect volume/issue/pages")
    return "Real work cited with substantive error(s): " + ", ".join(errs) + " (human-coded)."


def _is_dup(title: str, kept_titles: list[str]) -> bool:
    from rapidfuzz import fuzz

    t = title.lower().strip()
    if not t:
        return False
    return any(fuzz.token_sort_ratio(t, k) / 100.0 >= 0.95 for k in kept_titles)


def build_entries(
    rows: list[tuple[Any, ...]], added_date: str = "2026-07-10"
) -> tuple[list[BenchmarkEntry], dict[str, int]]:
    stats: dict[str, int] = {
        "total_articles": 0,
        "unusable": 0,
        "excluded_date_volpage": 0,
        "deduped_cross_version": 0,
        "valid": 0,
        "hallucinated": 0,
    }
    entries: list[BenchmarkEntry] = []
    kept_titles: list[str] = []
    for row in rows:
        if str(row[C_PUBTYPE]).strip() != "A":
            continue
        stats["total_articles"] += 1
        fields = parse_apa_article(str(row[C_CITE]))
        if not _parse_ok(fields):
            stats["unusable"] += 1
            continue

        label, htype, decision = classify(row)
        if decision == "date_or_volpage_only":
            stats["excluded_date_volpage"] += 1
            continue

        # Same work is sometimes cited by both GPT-3.5 and GPT-4 for one topic;
        # keep the first occurrence only (matches the benchmark's dedup rule).
        if _is_dup(fields["title"], kept_titles):
            stats["deduped_cross_version"] += 1
            continue
        kept_titles.append(fields["title"].lower().strip())

        gpt = str(row[C_GPT]).strip()
        cnum = f"{float(row[C_CNUM]):.2f}".replace(".", "")
        key = f"ww_{gpt.replace('.', '')}_t{row[C_TOPIC]}_c{cnum}"

        if label == "VALID":
            subtests: dict[str, bool | None] = dict(VALID_SUBTESTS)
            subtests["doi_resolves"] = None  # no DOI in source
            entries.append(
                BenchmarkEntry(
                    bibtex_key=key,
                    bibtex_type="article",
                    fields=fields,
                    label="VALID",
                    explanation="Real, verifiable article (human-coded, no substantive error).",
                    generation_method="llm_generated",
                    source="walters_wilder_2023",
                    added_to_benchmark=added_date,
                    subtests=subtests,
                    schema_version="1.0",
                )
            )
            stats["valid"] += 1
        else:
            assert htype is not None
            entries.append(
                BenchmarkEntry(
                    bibtex_key=key,
                    bibtex_type="article",
                    fields=fields,
                    label="HALLUCINATED",
                    hallucination_type=htype.value,
                    difficulty_tier=TIER[htype],
                    explanation=_explanation(row, htype),
                    generation_method="llm_generated",
                    source="walters_wilder_2023",
                    added_to_benchmark=added_date,
                    subtests=dict(EXPECTED_SUBTESTS[htype]),
                    schema_version="1.0",
                )
            )
            stats["hallucinated"] += 1
    return entries, stats


def load_rows(xlsx_path: Path) -> list[tuple[Any, ...]]:
    import openpyxl

    wb = openpyxl.load_workbook(xlsx_path, read_only=True)
    ws = wb[SHEET]
    rows = list(ws.iter_rows(values_only=True))
    return [r for r in rows[1:] if r[C_CITE]]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--xlsx", type=Path, default=None, help="Path to Appendix 3 .xlsx")
    ap.add_argument("--out", type=Path, required=True, help="Output JSONL path")
    args = ap.parse_args()

    xlsx_path = args.xlsx
    if xlsx_path is None:
        xlsx_path = Path("appendix3_walters_wilder.xlsx")
        if not xlsx_path.exists():
            print(f"Downloading Appendix 3 from {APPENDIX3_URL}")
            urllib.request.urlretrieve(APPENDIX3_URL, xlsx_path)

    rows = load_rows(xlsx_path)
    entries, stats = build_entries(rows)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w") as f:
        for e in entries:
            f.write(json.dumps(asdict(e)) + "\n")

    print(f"Wrote {len(entries)} entries -> {args.out}")
    for k, v in stats.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
